### PR TITLE
Update .gitignore

### PR DESCRIPTION
**Pull request by zheeeng**

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Is this related to `typescript`?

If so, it should be in the typescript template, not the default one.

Thanks!!

**Comment by chrisvxd** [comment]
Also seeing this after generating TS project, so imagine it's TS related.

**Comment by zheeeng** [comment]
It's `rollup` related

**Comment by transitive-bullshit** [comment]
`.rpt2_cache` was missing from a different gitignore since `.gitignore` is handled specially by the implementation.

Thanks for bringing this to my attention!

Fixed in `v2.6.6`.

It doesn't need to be in the default `.gitignore` because this is strictly related to [rollup-plugin-typescript2](https://github.com/ezolenko/rollup-plugin-typescript2).

**Pull request closed without merging**
