### PR TITLE
Add TypeScript support

### PR DESCRIPTION
**Pull request by kaltsimon**
Hi, I tried my hand at adding TypeScript support. Probably needs some more testing and maybe we could add tslint support, but I'd like to hear what you think.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Hey @kaltsimon, I really appreciate you putting this together. I meant to get back to you sooner, but such is life.

As far as the changes themselves go, I like the approach you took with adding another initialization option and separating the changes into a new template directory. It's exactly how I would've done it.

My only concern is that this will double the burden of maintenance for updating two templates instead of one. It's already been a bit annoying to make updates / fixes to react-modern-library-boilerplate and then carefully copy them into the template, and I'm worried about the additional duplication this would create on top of the duplication that's already there.

if you have any ideas on how to solve this duplication, I'm all ears. I'm not saying we shouldn't merge this; I just want to consider all the possibilities before going ahead.

**Comment by kaltsimon** [comment]
No worries. I understand your hesitation. I've also noticed that typescript tends to cause problems with the linked dependency as it uses the definitions in the node_modules folder of the library causing issues with duplicate definitions for React. So this is something that I'd need to work on before this could be merged anyways.

Maybe a possible solution would be that the CLI clones the react-modern-library-boilerplate repo (or a version of it) and adjusts it to the given parameters. Then we could use a separate repo for the typescript boilerplate.

**Comment by hyphaene** [comment]
> Maybe a possible solution would be that the CLI clones the react-modern-library-boilerplate repo (or a version of it) and adjusts it to the given parameters. Then we could use a separate repo for the typescript boilerplate.

As I'm working on a similar tool, I'd go for this idea, seems much more DRY/automated ;)

**Comment by transitive-bullshit** [comment]
this PR has been superseded by #37.

**Comment by transitive-bullshit** [comment]
Published as `v2.4.0` 👍

**Pull request closed without merging**
