### PR TITLE
add semantic release option

### PR DESCRIPTION
**Pull request by adekbadek**
As proposed in #113 , this PR adds an option to configure [semantic-release](https://semantic-release.gitbook.io/) when creating a library (as an opt-in feature).
It also fixes the tests setup.

### CODE REVIEW

**Comment by adekbadek** [comment]
Hi @transitive-bullshit, did you get a chance to look at this PR?

**Comment by adekbadek** [comment]
@transitive-bullshit ? is there anybody out there? 👻

**Comment by transitive-bullshit** [comment]
I'd honestly like to keep CRL as small and focused as possible, so this functionality is above & beyond what I'd want as options in the default template.

I am, however, not in a position to actively maintain CRL at this point, so @adekbadek if you're open to shepherding #136 through, then I'd be happy if you added this functionality as well.

See #171 for a general project status update.

Sorry it's taken so long to get back to you && thanks for all your hard work and interest in this project!

**Comment by transitive-bullshit** [comment]
We're not looking ot add any additional functionality to CRL as it's already been hard to maintain.

I finally got around to updating CRL and releasing `v3.0.0`. Please feel free to follow-up with an updated PR and sorry for taking so long to get back to you.

**Pull request closed without merging**
