### PR TITLE
Use CRA v2

### PR DESCRIPTION
**Pull request by wuweiweiwu**
closes: #77 

ran `npx create-react-app example` in the template directories and changed stuff to use handlebar templates

I'm not 100% how the tests work. They've been failing for:

screen shot 2018-10-09 at 11 54 37 pm

### CODE REVIEW

**Comment by Sharlaan** [comment]
Why use AVA instead of built-in Jest from CRA ?

also i think Jest from CRA is already integrated with ts-jest and Babel (to be verified)

**Comment by tchalvak** [comment]
Seems to generally make sense, though the build is failing above, of course.

**Comment by jamsesso** [comment]
Is there anything that you need help with in order to get this PR merged? I would really like to see CRA 2 support soon

**Comment by transitive-bullshit** [comment]
I appreciate all the effort on this, everyone.

Merging now and will get it back to a working state shortly.

**Pull request merged**
