### PR TITLE
The typescript mode doesn't use Typescript in the example create-react-app #118

### PR DESCRIPTION
**Pull request by nsisodiya**
I have converted the example folder to typescript mode.

### CODE REVIEW

**Comment by nsisodiya** [comment]
I tried running the `npm run test` on the current master branch and its failing.

**Comment by nsisodiya** [comment]
image

**Comment by transitive-bullshit** [comment]
Awesome, thanks @nsisodiya!

**Comment by nsisodiya** [comment]
@transitive-bullshit but build is failing.

**Comment by nsisodiya** [comment]
package-lock.json was missing. So I added.

**Comment by transitive-bullshit** [comment]
@nsisodiya would you mind adding it in a new PR? this one's already merged?

Thanks again!

**Comment by nsisodiya** [comment]
build started failing on this commit - when microbundle lib was updated. - https://github.com/transitive-bullshit/create-react-library/commit/d18f62e92ff166ce42b26b04b5057edc13f2152c
I don't know what changes are needed to fix it. will check.

**Comment by Muhammadinaam** [comment]
Still example project is not in typescript.

**Comment by psyycker** [comment]
I just had a look and it looks like it is typescript. Where do you see that?

**Comment by Muhammadinaam** [comment]
> I just had a look and it looks like it is typescript. Where do you see that?

Yes it is working. sorry for my previous message

**Pull request merged**
