### PR TITLE
WIP CRL v2

### LINKED ISSUE #104: Extracting scripts to improve maintainability of descendent projects
Hi! Thanks so much for this useful tool. 🌟 

What would you think about extracting some of the boilerplate code into a package, `react-scripts`-style? Then users could eject if they have something too custom they want to do.

My use case is for React packages which are occasionally touched. It would be ideal if I didn't have to manage quite so many dependency upgrades on each one, so the time spent is more focused on the code itself and less on the surrounding tooling.

I appreciate the traction this tool has and might be interested in helping with this.

### PR DESCRIPTION
**Pull request by transitive-bullshit**
This branch separates out the core dependencies and build logic into a `crl-scripts` package in a very similar way that `create-react-app` uses `react-scripts` to centralize all logic.

This will make upgrading and maintaining most CRL libraries much easier and give CRL more control over the bundling process so we can push incremental changes more frequently.

The goal is to be able to `eject` from using `crl-scripts` in very much the same way that CRA does, but this functionality is currently missing.

This change also updates the example apps to use CRA v2 and is a superset of https://github.com/transitive-bullshit/create-react-library/pull/134 and https://github.com/transitive-bullshit/create-react-library/pull/122.

I created one [issue](https://github.com/facebook/create-react-app/issues/6579) for some weird behavior I ran into with CRA v2 and local linking.

cc @paulmelnikow @wuweiweiwu @danielsogl @sag1v @tsiq-swyx would love to hear your guy's thoughts on this direction for CRL v2. Also very much looking for contributors who are interested in helping out with finalizing this PR.

Still TODO:
- [x] `eject` functionality
- [x] update unit tests for v2 changes
- [ ] update docs for v2 changes
- [x] Just have one template and infer whether the project is using TS or not in `crl-scripts` similar to how CRA and microbundle work

Fixes #104, #116, #67 (updating the version of rollup), #99, #119, 

Thanks!

### CODE REVIEW

**Comment by karl-run** [comment]
I gave it a quick test locally. Built with yarn. Windows 10 with git bash shell.

```$ node create-react-library/packages/create-react-library/index.js testcrl2
? Package Name testcrl2
? Package Description
? Author's GitHub Handle karl-run
? GitHub Repo Path karl-run/testcrl2
? License MIT
? Package Manager npm
? Template default
× Copying default template to C:\Users\k\git\testcrl2
Error: Lexical error on line 1. Unrecognized text.
  ╔ ╝   ╔   �╔  F
^
    at Parser.parseError (C:\Users\k\git\create-react-library\packages\cre
ate-react-library\node_modules\handlebars\dist\cjs\handlebars\compiler\par
ser.js:267:19)
    at Object.parseError (C:\Users\k\git\create-react-library\packages\cre
ate-react-library\node_modules\handlebars\dist\cjs\handlebars\compiler\par
ser.js:394:36)
    at Object.next (C:\Users\k\git\create-react-library\packages\create-re
act-library\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js
:522:33)
    at Object.lex (C:\Users\k\git\create-react-library\packages\create-rea
ct-library\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:
526:30)
    at lex (C:\Users\k\git\create-react-library\packages\create-react-libr
ary\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.js:297:36)
    at Parser.parse (C:\Users\k\git\create-react-library\packages\create-r
eact-library\node_modules\handlebars\dist\cjs\handlebars\compiler\parser.j
s:320:34)
    at HandlebarsEnvironment.parse (C:\Users\k\git\create-react-library\pa
ckages\create-react-library\node_modules\handlebars\dist\cjs\handlebars\co
mpiler\base.js:46:43)
    at compileInput (C:\Users\k\git\create-react-library\packages\create-r
eact-library\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler
.js:515:19)
    at ret (C:\Users\k\git\create-react-library\packages\create-react-libr
ary\node_modules\handlebars\dist\cjs\handlebars\compiler\compiler.js:524:1
8)
    at AsyncFunction.module.exports.copyTemplateFile (C:\Users\k\git\creat
e-react-library\packages\create-react-library\lib\create-library.js:89:21)`````

Maybe you'll find this helpful. :)

**Comment by sag1v** [comment]
Great progress. I hope i'll have time to deep dive on it later on this week

**Comment by transitive-bullshit** [comment]
@CarterMcAlister excited to see this get updated -- let me know if you run into any issues 😄

**Comment by transitive-bullshit** [comment]
I finally got around to updating CRL and releasing `v3.0.0`.

This release uses a minor fork of `microbundle` instead of doing everything ourselves which simplifies the amount of work we'll have to do to maintain CRL as well as libraries created with CRL.

**Pull request closed without merging**
