### PR TITLE
Adds ability to conditionally create a git repo

### PR DESCRIPTION
**Pull request by zachwolf**
Another PR coming in hot. 

The goal of this is to allow libraries to be generated in monorepos, without having their own git config. This also mirrors create-react-app's approach.

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
This looks great, as well. I'll take a look more in-depth tomorrow.

One thing I'd like is to keep the number of prompts as minimal as possible. Maybe it makes more sense to have this be just a CLI flag as opposed to adding it as a confirmation prompt?

**Comment by zachwolf** [comment]
That makes sense to me, I didn't want to break any existing patterns with my changes. Should I make that change?

**Comment by transitive-bullshit** [comment]
@zachwolf yes, let's go ahead and change this to be a CLI-only option.

Thanks!

**Comment by zachwolf** [comment]
@transitive-bullshit should be ready to check out again

**Comment by transitive-bullshit** [comment]
This looks perfect, dude -- thanks!

Will publish a new version of CRL shortly.

**Comment by transitive-bullshit** [comment]
Just published all your updates as `v2.6.0` -- thanks again, @zachwolf!

Very happy to work with you on future updates if you're interested :)

**Comment by zachwolf** [comment]
100%! I have some other ideas but was doing my best to not flood your emails lol

**Pull request merged**
