### PR TITLE
Add missing typescript configuration

### PR DESCRIPTION
**Pull request by JasonHeylon**
- .prettier.json => .prettierrc
- Add @types/jest for the annoying warning in test code
- Add @typescript-eslint related packages and config for typescript linting

### CODE REVIEW

**Comment by transitive-bullshit** [comment]
Hey @JasonHeylon, these changes look good but you made them to the `default` template when they should be in the `typescript` template.

Mind updating?

**Comment by JasonHeylon** [comment]
Hi @transitive-bullshit, I only rename `.prettier.json` to `.prettierrc` in `default` template, I found it when I doing the same modification in `typescript` template.  Need I do it in another pr?

**Comment by transitive-bullshit** [comment]
Ahh I missed that. Looks good && thanks!!

**Comment by transitive-bullshit** [comment]
Will publish with next version.

**Pull request merged**
